Download selic entries
marileize/selic pull request #4
Opened 2024-03-10 22:13 UTC by marileize

Created a method to research the SELIC's entries for a given period.

2024-03-10 22:24 UTC, adilsoncarvalho commented on src/selic-entries.ts
> +    params.append('dataFinal', finalDate);
You can also assign an object to be taken as the parameters.

```suggestion
    const params = new URLSearchParams(
        dataInicial: initialDate,
        dataFinal: finalDate,
    );
```

2024-03-10 22:34 UTC, adilsoncarvalho requested changes

2024-03-10 22:34 UTC, adilsoncarvalho commented on src/selic-entries.ts
> +    const params = new URLSearchParams;
You missed parenthesis when instantiating a new instance of a class. I'm surprised that that worked.

```suggestion
    const params = new URLSearchParams();
```

2024-03-10 22:34 UTC, adilsoncarvalho commented on src/selic-entries.ts
> +    return JSON.stringify(selic_entries);
Why are you converting a data object into a string? One should be able to consume the outcome as an object

```json
[
  {
    "data":"08/03/2024",
    "valor":"0.041957"
  }
]
````

and not as a string

```typescript
'[{"data":"08/03/2024","valor":"0.041957"}]'
```

2024-03-10 22:34 UTC, adilsoncarvalho commented on src/selic-entries.spec.ts
> +    expect(await selicEntries("08/03/2024","08/03/2024")).toBe('[{"data":"08/03/2024","valor":"0.041957"}]')
Why are we testing a string as the result of a method should return a json?

2024-03-10 22:34 UTC, adilsoncarvalho commented on src/selic-entries.spec.ts
> +test("Testing selicEntries function", async () => {
The test name is redundant. Can you make it more clear to what it does test?

2024-03-10 22:41 UTC, adilsoncarvalho commented
I added a line to your description:

![image](https://github.com/marileize/selic/assets/349796/98d7deba-0bbb-4fdd-a772-a1f166986d9a)

That line will [link this PR to the issue, and when this PR is merged, close that issue automatically](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

![image](https://github.com/marileize/selic/assets/349796/c0fb9795-42ba-4a6c-a0a4-690522833fbe)

2024-03-11 06:07 UTC, adilsoncarvalho commented on src/selic-entries.spec.ts
> +import { selicEntries } from "./selic-entries";
Hey, use single quotes whenever possible, ok?

```suggestion
// my fancy changes
import { selicEntries } from './selic-entries';
```

2024-03-11 06:13 UTC, adilsoncarvalho commented on src/selic-entries.spec.ts
> +    expect(await selicEntries("08/03/2024","08/03/2024")).toBe('[{"data":"08/03/2024","valor":"0.041957"}]')
Give it a read on how Jest do assertions: https://jestjs.io/docs/expect

There is one to compare objects that's neat.

2024-03-11 06:16 UTC, adilsoncarvalho commented on src/selic-entries.spec.ts
> +test("Testing selicEntries function", async () => {
Try to namespace tests. Something like

```typescript
describe("selicEntries", () => {
  test("whatever tests", () => {
    // my funky test code is here ;)
  });
});
```

2024-03-12 05:38 UTC, marileize commented
@adilsoncarvalho I want to add the API URL to a configuration file. Do you agree? If so, what is the recommended file?

2024-03-12 09:59 UTC, adilsoncarvalho commented
Usually in node we don't do configuration files, but rather, get them from the environment. 

I need to find the link from the best practices when deploying services.

2024-03-12 10:23 UTC, adilsoncarvalho requested changes

2024-03-12 10:23 UTC, adilsoncarvalho commented on src/selic-entries.spec.ts
> +    ];
This shouldn't be here. When declared here, it'll become global to all the tests in this scope.

2024-03-12 10:23 UTC, adilsoncarvalho commented on src/selic-entries.spec.ts
> +        expect(await selicEntries("08/03/2024","08/03/2024")).toMatchObject(desiredSelicEntrie);
It's better to make the expectations more explicit.

```suggestion
        expect(await selicEntries("08/03/2024","08/03/2024")).toEqual({
            "data": '08/03/2024',
            "valor": '0.041957',
        });
```

2024-03-12 10:23 UTC, adilsoncarvalho commented on src/selic-entries.ts
> +    url.search = params.toString();
While this syntax you've chosen is ok, it doesn't look as good as using a hash. See the [examples](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams#examples) below:

```javascript
// Retrieve params via url.search, passed into constructor
const url = new URL("https://example.com?foo=1&bar=2");
const params1 = new URLSearchParams(url.search);

// Get the URLSearchParams object directly from a URL object
const params1a = url.searchParams;

// Pass in a string literal
const params2 = new URLSearchParams("foo=1&bar=2");
const params2a = new URLSearchParams("?foo=1&bar=2");

// Pass in a sequence of pairs
const params3 = new URLSearchParams([
  ["foo", "1"],
  ["bar", "2"],
]);

// Pass in a record
const params4 = new URLSearchParams({ foo: "1", bar: "2" });
```

---

```suggestion
    url.search = new URLSearchParams({
        dataInicial: initialDate,
        dataFinal: finalDate,
    }).toString();
```

2024-03-12 10:23 UTC, adilsoncarvalho commented on src/selic-entries.ts
> +    return selic_entries;
Do we need this variable?

```suggestion
    return await response.json();
```

2024-03-12 10:27 UTC, adilsoncarvalho commented
- [ ] Read [How to Write a Git Commit Message](https://cbea.ms/git-commit/)

2024-03-13 06:07 UTC, adilsoncarvalho approved these changes
LGTM

2024-03-13 06:09 UTC, merged